[workspace]
resolver = "2"
members = [
    "smtp-message", "smtp-message/fuzz",
    "smtp-server-types",
    "smtp-server", "smtp-server/fuzz"
]

[profile.release]
lto = true

[profile.bench]
lto = true
